/**
 * NYAYAVAULT PERMISSIONED BLOCKCHAIN CONSENSUS TESTS
 * File: backend/src/blockchain/consensus/test/byzantine.spec.ts
 */

import { InMemoryNodeRegistry } from '../../identity/in-memory-node-registry';
import { createGenesisBlock, forgeBlock } from '../../ledger/block';
import { createLedgerTransaction, signTransaction } from '../../ledger/transaction';
import { LedgerNodeIdentity } from '../../ledger/types';
import { createBlockEndorsement, createBlockProposal } from '../endorsement-signer';
import { ProposalManager } from '../proposal-manager';
import { PoAConsensusEngine } from '../poa-consensus-engine';

describe('Byzantine Threat Model & Malicious Peer Resilience Engine', () => {
  let registry: InMemoryNodeRegistry;
  let consensusEngine: PoAConsensusEngine;
  let genesis = createGenesisBlock('nyayavault-mainnet-1');

  beforeEach(() => {
    registry = new InMemoryNodeRegistry();
    consensusEngine = new PoAConsensusEngine(registry);
    genesis = createGenesisBlock('nyayavault-mainnet-1');
  });

  function createTestBlock(caseId = 'CASE-BYZ-101') {
    const policeIdentity = registry.getNode('POLICE_NODE')!;
    const policeSigner: LedgerNodeIdentity = {
      nodeId: 'POLICE_NODE',
      name: 'Police Node',
      publicKeyPem: policeIdentity.keys[0].publicKeyPem,
      privateKeyPem: policeIdentity.privateKeysByVersion.get(1)!,
    };

    const unsignedTx = createLedgerTransaction({
      chainId: 'nyayavault-mainnet-1',
      txType: 'EVIDENCE_ANCHOR',
      originatingNode: 'POLICE_NODE',
      nonce: 1,
      payload: { caseId },
    });

    const tx = signTransaction(unsignedTx, policeSigner);
    return forgeBlock({ previousBlock: genesis, transactions: [tx], proposerNode: 'POLICE_NODE' });
  }

  it('rejects endorsement forged by a malicious node attempting to claim another nodeId identity', () => {
    const policeNode = registry.getNode('POLICE_NODE')!;
    const adminNode = registry.getNode('ADMIN_NODE')!;
    const block1 = createTestBlock();

    const proposal = createBlockProposal({
      proposerNode: policeNode,
      block: block1,
      policyId: 'STANDARD_ANCHOR',
      chainId: 'nyayavault-mainnet-1',
    });

    // Malicious ADMIN_NODE creates an endorsement claiming nodeId = 'PROSECUTION_NODE'
    const spoofedEndorsement = createBlockEndorsement({
      endorserNode: adminNode,
      proposal,
    });
    // Override claiming to be PROSECUTION_NODE
    (spoofedEndorsement as any).nodeId = 'PROSECUTION_NODE';

    const manager = new ProposalManager({
      localNode: policeNode,
      nodeRegistry: registry,
      chainId: 'nyayavault-mainnet-1',
    });

    manager.receiveProposal(proposal);

    const addRes = manager.addEndorsement(spoofedEndorsement);
    expect(addRes.valid).toBe(false);
    expect(['INVALID_ENDORSEMENT_SIGNATURE', 'ENDORSER_FINGERPRINT_MISMATCH']).toContain(addRes.code);
  });

  it('rejects endorsement generated by a disabled node', () => {
    const policeNode = registry.getNode('POLICE_NODE')!;
    const prosNode = registry.getNode('PROSECUTION_NODE')!;
    const block1 = createTestBlock();

    const proposal = createBlockProposal({
      proposerNode: policeNode,
      block: block1,
      policyId: 'STANDARD_ANCHOR',
      chainId: 'nyayavault-mainnet-1',
    });

    const endorsement = createBlockEndorsement({
      endorserNode: prosNode,
      proposal,
    });

    // Revoke key version 1 for PROSECUTION_NODE
    registry.revokeNodeKey('PROSECUTION_NODE', 1);

    const manager = new ProposalManager({
      localNode: policeNode,
      nodeRegistry: registry,
      chainId: 'nyayavault-mainnet-1',
    });

    manager.receiveProposal(proposal);

    const addRes = manager.addEndorsement(endorsement);
    expect(addRes.valid).toBe(false);
    expect(addRes.code).toBe('REVOKED_ENDORSER_KEY');
  });

  it('rejects endorsement from an unknown unregistered node', () => {
    const policeNode = registry.getNode('POLICE_NODE')!;
    const block1 = createTestBlock();

    const proposal = createBlockProposal({
      proposerNode: policeNode,
      block: block1,
      policyId: 'STANDARD_ANCHOR',
      chainId: 'nyayavault-mainnet-1',
    });

    const endorsement = createBlockEndorsement({
      endorserNode: policeNode,
      proposal,
    });

    // Change nodeId to unknown node
    (endorsement as any).nodeId = 'MALICIOUS_NODE';

    const manager = new ProposalManager({
      localNode: policeNode,
      nodeRegistry: registry,
      chainId: 'nyayavault-mainnet-1',
    });

    manager.receiveProposal(proposal);

    const addRes = manager.addEndorsement(endorsement);
    expect(addRes.valid).toBe(false);
    expect(addRes.code).toBe('UNREGISTERED_ENDORSER_NODE');
  });

  it('rejects malicious tampering of proposal transactions before endorsement collection', () => {
    const policeNode = registry.getNode('POLICE_NODE')!;
    const block1 = createTestBlock();

    const proposal = createBlockProposal({
      proposerNode: policeNode,
      block: block1,
      policyId: 'STANDARD_ANCHOR',
      chainId: 'nyayavault-mainnet-1',
    });

    // Malicious peer tampers transaction payload in block
    proposal.block.transactions[0].payload = { caseId: 'MALICIOUS-TAMPER' };

    const manager = new ProposalManager({
      localNode: policeNode,
      nodeRegistry: registry,
      chainId: 'nyayavault-mainnet-1',
    });

    const recRes = manager.receiveProposal(proposal);
    expect(recRes.valid).toBe(false);
    expect(recRes.code).toBe('INVALID_TRANSACTION_IN_BLOCK');
  });
});
